language: erlang
notifications:
  email: false
otp_release:
  - 17.4
after_success:
  - tools/travis_upload_release.sh
env:
  global:
    - TARBALL_NAME=mmserl_${TRAVIS_COMMIT:0:6}.tar.gz
  matrix:
    - SPEC=embedded
    - SPEC=spec1
    - SPEC=spec2
    - SPEC=spec3
